use-black256
extra-keys = [['ESC','/','-','HOME','UP','END','PGUP'],['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN'],['M','A','N','U','A','L',';'],['QUOTE','ENT','PIPE','LBR','RBR','DEL']]
extra-keys-text-all-caps = true
font-size = 10
bell-character = ignore
bell-vibrate = true
terminal-margin-horizontal = 4
terminal-margin-vertical = 8
use-fullscreen-workaround = true
